/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import DataExport.ExportToExcel;
import entity.DayRoute;
import entity.Destination;
import entity.LogRecord;
import entity.RouteRepository;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import limitingrules.UserLimitations;
import logbook.LogGenerator;
import org.joda.time.DateTime;
import org.joda.time.format.DateTimeFormat;
import org.joda.time.format.DateTimeFormatter;
import tripsgen.FrequencyType;
import tripsgen.UserInput;

/**
 *
 * @author himanshupahuja
 */
public class InterfaceTest extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceTest
     */
    public InterfaceTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        DeductableKms = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        DeductableKms1 = new javax.swing.JLabel();

        jFileChooser1.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooser1.setApproveButtonText("Save");
        jFileChooser1.setFileSelectionMode(javax.swing.JFileChooser.DIRECTORIES_ONLY);
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FolderSelected(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setText("5 Warley Road Malvern East VIC 3145");
        jScrollPane4.setViewportView(jTextArea4);

        jLayeredPane2.add(jScrollPane4);
        jScrollPane4.setBounds(0, 110, 250, 110);

        jLabel6.setText("Other Home Locations");
        jLayeredPane2.add(jLabel6);
        jLabel6.setBounds(0, 90, 126, 16);

        jTextField3.setText("80 Balcombe Road Mentone VIC 3194");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jTextField3);
        jTextField3.setBounds(0, 50, 250, 30);

        jLabel7.setText("Home Address");
        jLayeredPane2.add(jLabel7);
        jLabel7.setBounds(0, 30, 83, 16);

        jLabel4.setText("Work HQ Address");
        jLayeredPane2.add(jLabel4);
        jLabel4.setBounds(260, 30, 101, 16);

        jTextField2.setText("35 Koornang Road Scoresby VIC 3179");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jLayeredPane2.add(jTextField2);
        jTextField2.setBounds(260, 50, 255, 30);

        jLabel3.setText("Other Work Locations");
        jLayeredPane2.add(jLabel3);
        jLabel3.setBounds(260, 90, 141, 16);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("800 Stud Road Scoresby VIC 3179\n9 Helen Kob Drive Braeside VIC 3195\n91 Elizabeth St Melbourne VIC 3000");
        jScrollPane2.setViewportView(jTextArea2);

        jLayeredPane2.add(jScrollPane2);
        jScrollPane2.setBounds(260, 110, 255, 111);

        jLabel5.setText("Client Locations");
        jLayeredPane2.add(jLabel5);
        jLabel5.setBounds(520, 90, 141, 16);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("47 Robinson Street Dandenong VIC 3175\nMonash Caulfield VIC 3145");
        jScrollPane3.setViewportView(jTextArea3);

        jLayeredPane2.add(jScrollPane3);
        jScrollPane3.setBounds(530, 110, 255, 110);

        jLabel2.setText("Stage 1 : User Information and Addresses");
        jLayeredPane2.add(jLabel2);
        jLabel2.setBounds(0, 0, 360, 16);

        jCheckBox2.setText("Start At Any Work Location");
        jLayeredPane2.add(jCheckBox2);
        jCheckBox2.setBounds(520, 50, 230, 25);

        jLayeredPane1.setAutoscrolls(true);

        jLabel1.setText("Stage 2 : Unique Trips & Frequencies");
        jLayeredPane1.add(jLabel1);
        jLabel1.setBounds(0, 10, 360, 16);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Trip#", "Trip Desc.", "Distance Group", "Hops Group", "Overall Group"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLayeredPane1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 30, 550, 120);

        jButton1.setText("Validate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jLayeredPane1.add(jButton1);
        jButton1.setBounds(681, 0, 100, 25);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2", "3", "4", "5", "6" }));
        jComboBox1.setSelectedIndex(1);
        jLayeredPane1.add(jComboBox1);
        jComboBox1.setBounds(330, 0, 110, 22);

        jLabel12.setText("Cluster Size");
        jLayeredPane1.add(jLabel12);
        jLabel12.setBounds(270, 0, 110, 20);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Group Index", "Percentage"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(jTable4);

        jLayeredPane1.add(jScrollPane7);
        jScrollPane7.setBounds(570, 30, 210, 120);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Distance", "Hops", "Distance & Hops" }));
        jLayeredPane1.add(jComboBox2);
        jComboBox2.setBounds(530, 0, 110, 22);

        jLabel15.setText("Complexity By");
        jLayeredPane1.add(jLabel15);
        jLabel15.setBounds(460, 0, 110, 20);

        jLabel8.setText("Stage 3 : Diary Records & Calendar Preferences");
        jLayeredPane3.add(jLabel8);
        jLabel8.setBounds(10, 20, 360, 16);

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1-Sep-2013",  new Integer(1), null},
                {"17-Sep-2013",  new Integer(4), ""},
                {"28-Sep-2013",  new Integer(2), ""}
            },
            new String [] {
                "Date", "Trip#", "Trip Desc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable2);

        jLayeredPane3.add(jScrollPane5);
        jScrollPane5.setBounds(20, 50, 452, 90);

        jCheckBox1.setText("Travel on Weekends");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jLayeredPane3.add(jCheckBox1);
        jCheckBox1.setBounds(620, 10, 140, 25);

        jLabel10.setText("Log End Date");
        jLayeredPane3.add(jLabel10);
        jLabel10.setBounds(510, 70, 150, 20);

        jLabel11.setText("Desired Claim Percentage");
        jLayeredPane3.add(jLabel11);
        jLabel11.setBounds(320, 10, 150, 20);

        jTextField1.setText("1-Aug-2013");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jLayeredPane3.add(jTextField1);
        jTextField1.setBounds(620, 40, 130, 22);

        jTextField4.setText("30-Oct-2013");
        jLayeredPane3.add(jTextField4);
        jTextField4.setBounds(620, 70, 130, 22);

        jLabel13.setText("Odometer Start");
        jLayeredPane3.add(jLabel13);
        jLabel13.setBounds(510, 100, 100, 20);

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jLayeredPane3.add(jTextField5);
        jTextField5.setBounds(620, 100, 130, 22);

        jLabel14.setText("Odometer End");
        jLayeredPane3.add(jLabel14);
        jLabel14.setBounds(510, 130, 99, 20);

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jLayeredPane3.add(jTextField6);
        jTextField6.setBounds(620, 130, 130, 22);

        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jLayeredPane3.add(jTextField7);
        jTextField7.setBounds(480, 10, 80, 22);

        jLabel16.setText("Log Start Date");
        jLayeredPane3.add(jLabel16);
        jLabel16.setBounds(510, 40, 150, 20);

        jLabel9.setText("Stage 4 : Log Book Results");
        jLayeredPane4.add(jLabel9);
        jLabel9.setBounds(0, 10, 360, 16);

        jTable3.setAutoCreateRowSorter(true);
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Trip", "Total Kms", "Total Deductable"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable3);

        jLayeredPane4.add(jScrollPane6);
        jScrollPane6.setBounds(10, 30, 770, 110);

        jButton2.setText("Generate LogBook");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jLayeredPane4.add(jButton2);
        jButton2.setBounds(620, 150, 160, 25);

        DeductableKms.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DeductableKms.setText("KMs");
        DeductableKms.setToolTipText("");
        DeductableKms.setName("DeductableKMS"); // NOI18N
        jLayeredPane4.add(DeductableKms);
        DeductableKms.setBounds(200, 170, 400, 15);

        jLabel17.setText("Total claimable Kms in this run : ");
        jLabel17.setToolTipText("");
        jLayeredPane4.add(jLabel17);
        jLabel17.setBounds(10, 170, 200, 16);

        jButton3.setText("Export");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jLayeredPane4.add(jButton3);
        jButton3.setBounds(620, 180, 160, 25);

        DeductableKms1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DeductableKms1.setText("KMs");
        DeductableKms1.setToolTipText("");
        DeductableKms1.setName("DeductableKMS"); // NOI18N
        jLayeredPane4.add(DeductableKms1);
        DeductableKms1.setBounds(10, 190, 400, 15);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLayeredPane1)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLayeredPane4)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jLayeredPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 784, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 0, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLayeredPane3))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLayeredPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 228, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 172, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLayeredPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 178, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLayeredPane4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                .add(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        ArrayList <Destination>WorkAddresses = new ArrayList();
        ArrayList <Destination>HomeAddresses = new ArrayList();
        
        
        Destination home = new Destination(this.jTextField3.getText(),false,true,false);
        Destination workHQ = new Destination(this.jTextField2.getText(),false,false,true);
        
        System.out.println(" H : " + this.jTextField3.getText());
        System.out.println(" HQ : " + this.jTextField2.getText());
       
        
        String []hads = this.jTextArea4.getText().split("\n");
        
        for(String h : hads)
        {
            System.out.println(" H : " + h);
            HomeAddresses.add(new Destination(h,false,true,false));
        }
        
        
        String []wads = this.jTextArea2.getText().split("\n");
        
        for(String s : wads)
        {
            System.out.println(" W : " + s);
            WorkAddresses.add(new Destination(s,false,false,true));
        }
        
        String []cads = this.jTextArea3.getText().split("\n");
        
        for(String c : cads)
        {
            System.out.println(" C : " + c);
            WorkAddresses.add(new Destination(c,true,false,false));
        } 
        
        ui = new UserInput(home,workHQ,WorkAddresses,HomeAddresses,this.jCheckBox2.isSelected());
        
        repo = ui.DistinctRoutes(50);
        
        repo.UpdateRouteDistances();
        repo.print();
        System.out.println("Net Distinct Routes : " + repo.GetSize());
        
        
        //repo.AllocateRandomFrequencies();
        repo = ui.ProfileRouteRepository(repo, Integer.parseInt(this.jComboBox1.getSelectedItem().toString()));
        
        
        
        
        
        Object [][] tableData ;
        String [] columnData = {"Trip#","Trip Desc.","Distance Group","Hop Group","Overall Group"};
        int count = 0;
        int totalRecords = repo.GetSize();
        tableData =  new Object[totalRecords][5];
        
        
        for(DayRoute dr : repo.GetRepo())
        {
            tableData[count][0] = count + 1;
            tableData[count][1] = dr.GetTrip();
            tableData[count][2] = dr.GetDistGroupIndex();
            tableData[count][3] = dr.GetHopGroupIndex();
            tableData[count][4] = dr.GetGroupIndex();
            
            count++;
        }
        
         this.jTable1.setModel(new DefaultTableModel(tableData,columnData));
         this.jTable1.repaint();
        
         
        Object [][] LoadData ;
        String [] columnLoads = {"Group Index","Group Load"};
        int Loadcount = 0;
        int LoadtotalRecords = Integer.parseInt(this.jComboBox1.getSelectedItem().toString());
        LoadData =  new Object[LoadtotalRecords][2];
        
        for(int i=0;i<LoadtotalRecords;i++)
        {
            LoadData[i][0] = i; 
        }
        
        this.jTable4.setModel(new DefaultTableModel(LoadData,columnLoads));
        this.jTable4.repaint();
         
         
        System.out.println("Done !");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        
        
        
        
        
        
        
        
        
        
        
        UserLimitations restr = new UserLimitations(this.jCheckBox1.isSelected());
        DateTimeFormatter dstrFmt = DateTimeFormat.forPattern("dd-MMM-yyyy");
        DateTime tempDate;
        DayRoute dr;
        int routeRef;
        
        
        
        
        
        
        for(int i=0;i<this.jTable2.getModel().getRowCount();i++)
        {
            tempDate = dstrFmt.parseDateTime(String.valueOf(this.jTable2.getModel().getValueAt(i, 0)));
            routeRef = Integer.parseInt(this.jTable2.getModel().getValueAt(i,1).toString()); 
            dr = repo.GetRoute(routeRef-1);
            LogRecord lr = new LogRecord(dr,tempDate);
            restr.AddRecord(lr);
        }
        
        
        DateTime startOn = dstrFmt.parseDateTime(this.jTextField1.getText());
        DateTime endOn = dstrFmt.parseDateTime(this.jTextField4.getText());
        
        
        int countIncrement = 0 ;
        boolean upd = false;
        int setIncr = -10;
        double maxP=0.0;
        
        ArrayList<Double> loadingList = new ArrayList();
            
        if(Double.parseDouble(this.jTextField7.getText())>0)
        {
            loadingList.add(50.0);
            loadingList.add(30.0);
            loadingList.add(20.0);
            
            
        }
        else
        {
            
            double RegionValue = 0.0;
            for(int i=0;i<this.jTable4.getModel().getRowCount();i++)
            {
                RegionValue += Double.parseDouble(this.jTable4.getModel().getValueAt(i, 1).toString());
                loadingList.add(RegionValue);
            }
        }
        
        ArrayList<Double> itr = loadingList;
        boolean loopBrk = false;
        
        for(int i=0;i<20;i++)
        {
            if(!loopBrk)
            {
//            upd = false;
//            for(Double d : itr)
//            {
//                if(d < 100 && upd == false && d+setIncr >= 0 && itr.indexOf(d) >= countIncrement)
//                {
//                    itr.set(itr.indexOf(d), d + setIncr);
//                    upd = true;
//                    countIncrement = itr.indexOf(d);
//                }
//                
//                if( d == 0 && upd == false)
//                {
//                    setIncr = 10;
//                    countIncrement++;
//                }
//                
//            }
        
        if(itr.get(countIncrement)>=10 && countIncrement < itr.size()-1)
        {
            
            itr.set(countIncrement, itr.get(countIncrement)-10);
        }   
        else
        {
            if(countIncrement < itr.size()-1)
            {
                countIncrement++;
            }
            //itr.set(countIncrement, itr.get(countIncrement)-10);
        }
            
        print(itr);
        repo.SetGroupLoading(itr);
        
        
        
        lg = new LogGenerator(repo, startOn,endOn,restr,GetMode(this.jComboBox2.getSelectedIndex()));
        lg.Allocate();
        
        ArrayList<LogRecord> result = lg.GetRecords();
        
        Object [][] tableData ;
        String [] columnData = {"Date","Trip Desc.","Total Kms","Total Deductable Kms"};
        int count = 0;
        int totalRecords = result.size();
        double TotalDeductable = 0.0,TotalDistance = 0.0;
        tableData =  new Object[totalRecords][4];
        
        
        for(LogRecord l : result)
        {
            tableData[count][0] = l.GetDate().toString(DateTimeFormat.forPattern("dd-MMM-yyyy"));
            tableData[count][1] = l.GetTrip();
            tableData[count][2] = Math.round(l.GetDistance());
            tableData[count][3] = Math.round(l.GetDeductableDistance());
            TotalDistance += Math.round(l.GetDistance());
            TotalDeductable += Math.round(l.GetDeductableDistance());
            count++;
        }
        
         this.jTable3.setModel(new DefaultTableModel(tableData,columnData));
         this.jTable3.repaint();
        
         this.DeductableKms.setText(String.valueOf(TotalDeductable) + " of Total : " + String.valueOf(TotalDistance) + " :  Percentage = " + String.valueOf(TotalDeductable*100/TotalDistance));
         this.repaint();
         
         System.out.println(String.valueOf(TotalDeductable) + " of Total : " + String.valueOf(TotalDistance) + " :  Percentage = " + String.valueOf(TotalDeductable*100/TotalDistance));
         
         if(maxP < TotalDeductable*100/TotalDistance)
         {
             maxP = TotalDeductable*100/TotalDistance;
         }
        
        }    
        
        this.DeductableKms1.setText("Max Achievable with this data set : " + maxP + "%");

        
        if(maxP >= Double.parseDouble(this.jTextField7.getText()))
        {
            loopBrk = true;
        }
            
            
        }
        
       
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    
    public void print(ArrayList<Double> ll)
    {
        for(Double d : ll)
        {
            System.out.println(" Item at : " + ll.indexOf(d) + " - " + d);
        }
    }
    
    
    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void FolderSelected(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FolderSelected
        // TODO add your handling code here:
        
        System.out.println(" Source : " + evt.getSource() + "  :  " + evt.getSource().toString()+ ":" + evt.getActionCommand());
        File f = this.jFileChooser1.getSelectedFile();
        
            if(f.isDirectory())
            {
                System.out.println("Call Exporter");
                ExportToExcel exporter = new ExportToExcel(f.getPath() + "\\LogBookExport");
                exporter.ExportRoutes("RouteList", repo.GetRouteList());
                exporter.ExportLogBook("LogBook", lg.GetRecords(),Double.parseDouble(this.jTextField5.getText()),Double.parseDouble(this.jTextField6.getText()));
                exporter.CommitWorkBook();
            }
        
    }//GEN-LAST:event_FolderSelected

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         this.jFileChooser1.showSaveDialog(this);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceTest().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DeductableKms;
    private javax.swing.JLabel DeductableKms1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    // End of variables declaration//GEN-END:variables

    private UserInput ui;
    private RouteRepository repo;
    private LogGenerator lg;

    private String GetMode(int selectedIndex) {
        switch(selectedIndex)
        {
            case 0 : return "DIST";
                     
            case 1 : return "HOPS";
                
            case 2 : return "DISTHOPS";
                
            default : return "NA";
        }
    }
    
}
