/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import entity.DayRoute;
import entity.Destination;
import entity.LogRecord;
import entity.RouteRepository;
import java.util.ArrayList;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import limitingrules.UserLimitations;
import logbook.LogGenerator;
import org.joda.time.DateTime;
import org.joda.time.format.DateTimeFormat;
import org.joda.time.format.DateTimeFormatter;
import tripsgen.FrequencyType;
import tripsgen.UserInput;

/**
 *
 * @author himanshupahuja
 */
public class InterfaceTest extends javax.swing.JFrame {

    /**
     * Creates new form InterfaceTest
     */
    public InterfaceTest() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane2 = new javax.swing.JLayeredPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jScrollPane4.setBounds(0, 110, 250, 110);
        jLayeredPane2.add(jScrollPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel6.setText("Other Home Locations");
        jLabel6.setBounds(0, 90, 141, 16);
        jLayeredPane2.add(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField3.setText("80 Balcombe Road Mentone VIC 3194");
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jTextField3.setBounds(0, 50, 250, 28);
        jLayeredPane2.add(jTextField3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel7.setText("Home Address");
        jLabel7.setBounds(0, 30, 92, 16);
        jLayeredPane2.add(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel4.setText("Work HQ Address");
        jLabel4.setBounds(260, 30, 111, 16);
        jLayeredPane2.add(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField2.setText("35 Koornang Road Scoresby VIC 3179");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jTextField2.setBounds(260, 50, 255, 28);
        jLayeredPane2.add(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setText("Other Work Locations");
        jLabel3.setBounds(260, 90, 141, 16);
        jLayeredPane2.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("800 Stud Road Scoresby VIC 3179");
        jScrollPane2.setViewportView(jTextArea2);

        jScrollPane2.setBounds(260, 110, 255, 111);
        jLayeredPane2.add(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel5.setText("Client Locations");
        jLabel5.setBounds(520, 90, 141, 16);
        jLayeredPane2.add(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("47 Robinson Street Dandenong VIC 3175");
        jScrollPane3.setViewportView(jTextArea3);

        jScrollPane3.setBounds(520, 110, 255, 110);
        jLayeredPane2.add(jScrollPane3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Validate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jButton1.setBounds(660, 0, 94, 29);
        jLayeredPane2.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setText("Stage 1 : User Information and Addresses");
        jLabel2.setBounds(0, 0, 360, 16);
        jLayeredPane2.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jCheckBox2.setText("Start At Any Work Location");
        jCheckBox2.setBounds(520, 50, 230, 23);
        jLayeredPane2.add(jCheckBox2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane1.setAutoscrolls(true);

        jLabel1.setText("Stage 2 : Unique Trips & Frequencies");
        jLabel1.setBounds(0, 10, 360, 16);
        jLayeredPane1.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null}
            },
            new String [] {
                "Trip#", "Trip Desc.", "Frequency Type", "Frequency"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jScrollPane1.setBounds(10, 30, 770, 120);
        jLayeredPane1.add(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel8.setText("Stage 3 : Diary Records & Calendar Preferences");
        jLabel8.setBounds(0, 10, 360, 16);
        jLayeredPane3.add(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTable2.setAutoCreateRowSorter(true);
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1-Sep-2013",  new Integer(1), null},
                {"17-Sep-2013",  new Integer(4), ""},
                {"28-Sep-2013",  new Integer(2), ""}
            },
            new String [] {
                "Date", "Trip#", "Trip Desc"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jTable2);

        jScrollPane5.setBounds(10, 40, 454, 90);
        jLayeredPane3.add(jScrollPane5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jCheckBox1.setText("Travel on Weekends");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jCheckBox1.setBounds(580, 40, 190, 23);
        jLayeredPane3.add(jCheckBox1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel10.setText("Log End Date");
        jLabel10.setBounds(470, 90, 150, 16);
        jLayeredPane3.add(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel11.setText("Log Start Date");
        jLabel11.setBounds(470, 70, 150, 16);
        jLayeredPane3.add(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton2.setText("Generate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jButton2.setBounds(670, 10, 99, 29);
        jLayeredPane3.add(jButton2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField1.setText("1-Sep-2013");
        jTextField1.setBounds(580, 60, 200, 28);
        jLayeredPane3.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField4.setText("30-Sep-2013");
        jTextField4.setBounds(580, 90, 200, 28);
        jLayeredPane3.add(jTextField4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel9.setText("Stage 4 : Log Book Results");
        jLabel9.setBounds(0, 10, 360, 16);
        jLayeredPane4.add(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTable3.setAutoCreateRowSorter(true);
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Trip", "Total Kms", "Total Deductable"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jTable3);

        jScrollPane6.setBounds(10, 30, 770, 140);
        jLayeredPane4.add(jScrollPane6, javax.swing.JLayeredPane.DEFAULT_LAYER);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLayeredPane1)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLayeredPane4)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(jLayeredPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 784, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(0, 0, Short.MAX_VALUE))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jLayeredPane3))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLayeredPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 228, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLayeredPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 155, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLayeredPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 141, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLayeredPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 176, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        ArrayList <Destination>WorkAddresses = new ArrayList();
        ArrayList <Destination>HomeAddresses = new ArrayList();
        
        
        Destination home = new Destination(this.jTextField3.getText(),false,true,false);
        Destination workHQ = new Destination(this.jTextField2.getText(),false,false,true);
        
        System.out.println(" H : " + this.jTextField3.getText());
        System.out.println(" HQ : " + this.jTextField2.getText());
       
        
        String []hads = this.jTextArea4.getText().split("\n");
        
        for(String h : hads)
        {
            System.out.println(" H : " + h);
            //HomeAddresses.add(new Destination(h,false,true,false));
        }
        
        
        String []wads = this.jTextArea2.getText().split("\n");
        
        for(String s : wads)
        {
            System.out.println(" W : " + s);
            WorkAddresses.add(new Destination(s,false,false,true));
        }
        
        String []cads = this.jTextArea3.getText().split("\n");
        
        for(String c : cads)
        {
            System.out.println(" C : " + c);
            WorkAddresses.add(new Destination(c,true,false,false));
        } 
        
        ui = new UserInput(home,workHQ,WorkAddresses,HomeAddresses,this.jCheckBox2.isSelected());
        
        repo = ui.DistinctRoutes(50);
        
        repo.UpdateRouteDistances();
        repo.print();
        System.out.println("Net Distinct Routes : " + repo.GetSize());
        
        
        repo.AllocateRandomFrequencies();
        
        Object [][] tableData ;
        String [] columnData = {"Trip#","Trip Desc.","Frequency Type","Frequency"};
        int count = 0;
        int totalRecords = Integer.parseInt(repo.GetSize());
        tableData =  new Object[totalRecords][4];
        
        
        for(DayRoute dr : repo.GetRepo())
        {
            tableData[count][0] = count + 1;
            tableData[count][1] = dr.GetTrip();
            tableData[count][2] = FrequencyType.GetCode(dr.GetFrequencyType());
            tableData[count][3] = dr.GetFrequencyLimit();
            
            count++;
        }
        
         this.jTable1.setModel(new DefaultTableModel(tableData,columnData));
         this.jTable1.repaint();
        
        System.out.println("Done !");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
        UserLimitations restr = new UserLimitations(this.jCheckBox1.isSelected());
        DateTimeFormatter dstrFmt = DateTimeFormat.forPattern("dd-MMM-yyyy");
        DateTime tempDate;
        DayRoute dr;
        int routeRef;
        
        for(int i=0;i<this.jTable2.getModel().getRowCount();i++)
        {
            tempDate = dstrFmt.parseDateTime(String.valueOf(this.jTable2.getModel().getValueAt(i, 0)));
            routeRef = Integer.parseInt(this.jTable2.getModel().getValueAt(i,1).toString()); 
            dr = repo.GetRoute(routeRef-1);
            LogRecord lr = new LogRecord(dr,tempDate);
            restr.AddRecord(lr);
        }
        
        
        DateTime startOn = dstrFmt.parseDateTime(this.jTextField1.getText());
        DateTime endOn = dstrFmt.parseDateTime(this.jTextField4.getText());
        
        
        LogGenerator lg = new LogGenerator(repo, startOn,endOn,restr);
        lg.Allocate();
        
        ArrayList<LogRecord> result = lg.GetRecords();
        
        Object [][] tableData ;
        String [] columnData = {"Date","Trip Desc.","Total Kms","Total Deductable Kms"};
        int count = 0;
        int totalRecords = result.size();
        tableData =  new Object[totalRecords][4];
        
        
        for(LogRecord l : result)
        {
            tableData[count][0] = l.GetDate().toString(DateTimeFormat.forPattern("dd-MMM-yyyy"));
            tableData[count][1] = l.GetTrip();
            tableData[count][2] = Math.round(l.GetDistance());
            tableData[count][3] = Math.round(l.GetDeductableDistance());
            
            count++;
        }
        
         this.jTable3.setModel(new DefaultTableModel(tableData,columnData));
         this.jTable3.repaint();
        
        System.out.println("Done !");
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceTest().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

    private UserInput ui;
    private RouteRepository repo;
    
}
